project_id = "rlucmlnjoausnbnexvts"

[functions.send-contact-reply-email]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.parse-trade-file]
verify_jwt = false

[functions.mt-webhook]
verify_jwt = false
